version: '3.8'

services:
  testrunner-app:
    image: testrunner-app # Use the locally built image
    container_name: testrunner-app
    ports:
      - "8080:8080"
    networks:
      - testrunner-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - testrunner-network

networks:
  testrunner-network:
    driver: bridge